# Generated by Django 5.1 on 2024-09-03 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(default=11111111111, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
