# Generated by Django 5.1 on 2024-09-09 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='stars',
            new_name='star',
        ),
    ]
